# Generated by Django 4.0.3 on 2022-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='region',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='response',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='uptime',
        ),
        migrations.AddField(
            model_name='proxy',
            name='speed',
            field=models.PositiveIntegerField(
                blank=True, help_text='in ms', null=True
            ),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='anonymity',
            field=models.CharField(
                blank=True,
                choices=[
                    (None, 'No'),
                    ('Low', 'Low'),
                    ('Average', 'Average'),
                    ('High', 'High'),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='protocol',
            field=models.CharField(
                choices=[
                    ('HTTP', 'HTTP'),
                    ('HTTPS', 'HTTPS'),
                    ('SOCKS4', 'SOCKS4'),
                    ('SOCKS5', 'SOCKS5'),
                ],
                default='HTTP',
                max_length=6,
            ),
        ),
    ]
